name: 🙏🏻 Lint Test
on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24.x
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: latest
          args: --timeout 5m
          working-directory: .
